### ISSUE TITLE
Suggested docs changes

### ISSUE THREAD

**Issue by bpiv400** [flox/nixexprs#19]
Recommended changes for docs under: https://github.com/flox/nixexprs/tree/staging/docs

**Comment by bpiv400** [comment]
Either in the README or channel-construction: What is channel construction? Why should I care about it? 

It's not defined anywhere, and there are no links to Nix documentation to define it.

**Comment by bpiv400** [comment]
Two bullets in first section of [README](https://github.com/flox/nixexprs/blob/staging/docs/readme.md) are syntactically inconsistent. 

> The outputs of the flox channel itself, such as builders like flox.mkDerivation and others. See here for reference documentation on this.

Should be changed to something like "Containing the outputs..." or "Defining the outputs..."

**Comment by bpiv400** [comment]
In https://github.com/flox/nixexprs/blob/staging/docs/channel-construction.md

>Each subdirectory allows specifying a package set where each package has a corresponding to the file it is defined in.

What does the "file it is defined in" mean? Would an example help here?

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/channel-construction.md

Should "overriding" be defined explicitly before explaining the difference between shallow and deep overriding?

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/channel-construction.md#shallow-vs-deep-overriding

I recommend linking the "expl" doc about deep overriding somewhere in the section, eg: 

"Check out this doc to learn more about how deep overriding works under the hood"

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/channel-construction.md#shallow-vs-deep-overriding

I recommend explicitly pulling out definitions and usage guidance of shallow and deep overriding, then explaining tradeoffs after both have been defined. 

* **Shallow overriding**:  Only overrides package in  the immediate dependencies of the channel. This is enabled by default. 
* **Deep Overriding**: Overrides packages transitively in all dependencies 

Shallow overriding uses mostly precompiled dependencies, while deep overriding could rebuild many layers of dependencies, so shallow overriding is cheaper to build. Deep overriding resolves version conflicts caused by multiple versions of the same dependency in a closure.

**Comment by bpiv400** [comment]
Either in https://github.com/flox/nixexprs/blob/staging/docs/channel-construction.md or https://github.com/flox/nixexprs/blob/staging/docs/package-sets.md, define "package sets" or link to a definition

**Comment by bpiv400** [comment]
> The <flox/channel> mechanism…

What is this mechanism? What does it do? Maybe link to documentation of channel construction and add explanatory content there.

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/name-inference.md#why-the-channel-name-is-needed-at-all

%s/in order for/for/g

**Comment by bpiv400** [comment]
Not a docs question: https://github.com/flox/nixexprs/blob/staging/docs/expl/name-inference.md

Why do we use a template to generate the nixexprs directory? Couldn't this problem be solved if users initialized their Nixexprs directory using a flox CLI where they could feed their org name with a better UX than copying and editing a github template?

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/name-inference.md

> then it can happen that we change a package in A, but that the change isn't propagated to B

I recommend  "then we can change a package in A without that change propagating to B" for reducing unnecessary words

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/name-inference.md

I don't really understand the dependency cycles pictures, though I understand the written description

Maybe we could add a legend or example names for the packages to distinguish between the two packages mentioned in A?

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/name-inference.md

Switch the order of the sections -> Justification first then explanation of complications?

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/call-scope.md

> the representative attribute name for that package set….is set to the correct version of the set. The same for channels.<name>.pythonPackages

I'm not sure what this means. HOw do we know what's "correct"?

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/call-scope.md

%s/in order to/to/g

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/channel-discovery.md

"Why channel discovery is done the way it is" -> Channel Discovery Mechanism and Motivation

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/channel-discovery.md

"There are a number of impurities that could be used for this, however this brings us to the next limiting factor: It needs to also work in Hydra, so that the channels can be built by it."  --> "We could use a number of impurities for this, but whichever we choose needs to be compatible with Hydra for building channels." (Changing passive to active voice and shortening)

**Comment by bpiv400** [comment]
https://github.com/flox/nixexprs/blob/staging/docs/expl/channel-discovery.md

%s/in order to/to/g

**Comment by Infinisil** [comment]
> Not a docs question: https://github.com/flox/nixexprs/blob/staging/docs/expl/name-inference.md
> 
> Why do we use a template to generate the nixexprs directory? Couldn't this problem be solved if users initialized their Nixexprs directory using a flox CLI where they could feed their org name with a better UX than copying and editing a github template?

Good question. I discussed this with @limeytexan before, and the main reason we don't want to do this is because such a CLI needs GitHub permissions for creating repositories, which are also the permissions for updating and deleting repositories, so a pretty heavy permission. And setting up this permission would be another step in the installation, which arguably is more work than just letting the user create the repository from a template.
